### ISSUE TITLE
Registration of connector does not work when installed via pip

### ISSUE THREAD

**Issue by FrancescAlted** [PyTables/datasette-pytables#8]
It seems that installing the connector via pip is not enough for registering the connector:

```
$ datasette serve table3.h5 
Serve! files=('table3.h5',) on port 8001
Traceback (most recent call last):
  File "/Users/faltet/miniconda3/bin/datasette", line 11, in <module>
    load_entry_point('datasette-core==0.22.1', 'console_scripts', 'datasette')()
<snip>
  File "/Users/faltet/miniconda3/lib/python3.6/site-packages/datasette_core-0.22.1-py3.6.egg/datasette/connectors.py", line 16, in inspect
    raise Exception("No database connector found for %s" % path)
Exception: No database connector found for table3.h5
```

However, when installing the package using regular setup.py:

```
$ python setup.py install
```

then it works:

```
$ datasette serve table3.h5 
Serve! files=('table3.h5',) on port 8001
[2018-06-01 13:39:56 +0200] [68744] [INFO] Goin' Fast @ http://127.0.0.1:8001
[2018-06-01 13:39:56 +0200] [68744] [INFO] Starting worker [68744]
```

**Comment by jsancho-gpl** [comment]
It's very weird! I only do `pip install datasette-pytables` and I have all the environment ready. Can you post more info like Python version or architecture?
